
target 'chatApp' do
  use_frameworks!
pod 'Firebase/Core', '~> 6.2.0'

#  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
#
#  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
#
#  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'

  pod 'GoogleSignIn', '~> 4.4.0'
  pod 'Firebase/Firestore', '~> 6.2.0'
  pod 'Firebase/Auth', '~> 6.2.0'

end
